

ATMCO = "ATMCO"
VENUE_SMART = "VENUE_SMART"
CASH_POINT = "CASH_POINT"
BANK_ACCOUNT = "Bank Account"
FIXES_HEADER_COMPANY_NAME = "ATM_SOLUTIONS_COMPANY(1=ATMCO, 2=VENUE_SMART, 3=CASHPOINT"
FIXES_HEADER_ERROR_DATE = "ERROR_DATE"
FIXES_HEADER_ERROR_TYPE="ERROR_TYPE(1=CHANGE_DESCRIPTION, 2=TID_CHANGE, 3=INSERT_NEW_TRANSACTION, 4=DELETE_ROW)"
FIXES_HEADER_EXISTING_REF = "EXISTING_REFERENCE"
FIXES_HEADER_INSERTED_AMOUNT = "INSERTED_AMOUNT"
FIXES_HEADER_INSERTED_CREDIT_DEBIT = "INSERTED_CREDIT_DEBIT (1=DEBIT, 2=CREDIT)"
FIXES_HEADER_INSERTED_REF = "INSERTED_REFERENCE"
